import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '40-50',
    price: 250,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: '../../../../../../../../assets/food/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
    calories: 2500,
    sizes: ["Small", "Medium", "Large"],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 300,
    cookTime: '30-50',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: '../../../../assets/food/food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
    calories: 400,
    sizes: ["Small", "Medium", "Large"],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 250,
    cookTime: '20-40',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: '../../../../assets/food/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
    calories: 500,
    sizes: ["Small", "Medium", "Large"],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 100,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: '../../../../assets/food/food-4.jpg',
    tags: ['FastFood', 'Fry'],
    calories: 500,
    sizes: ["Small", "Medium", "Large"],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 150,
    cookTime: '30-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: '../../../../assets/food/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
    calories: 600,
    sizes: ["Small", "Medium", "Large"],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 400,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: '../../../../assets/food/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
    calories: 1500,
    sizes: ["Small", "Medium", "Large"],
  },
]

export const sample_tags:Tag[] = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
]